name: Make test release package of ${{ github.ref }}

on:
  push:
    tags:
      - 'testing/v*' # e.g. testing/v2_6_4

jobs:
  build:
    name: Build ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q
          sudo apt-get install --no-install-recommends -q -y build-essential git bison autoconf ruby p7zip-full curl
      - name: Checkout ruby/ruby for tool/make-snapshot
        run: git clone --depth=1 https://github.com/ruby/ruby ruby
      - name: Make pkg ${{ github.ref }}
        run: |
          set -x
          TARGET_VERSION=$(echo $GITHUB_REF | sed -e "s#refs/tags/testing/v##" -e "s/_\([a-z]\)/-\1/" -e "y/_/./")
          ruby ruby/tool/make-snapshot -svn pkg ${TARGET_VERSION}
      - name: Check pkg
        run: |
          set -x
          TARGET_VERSION=$(echo $GITHUB_REF | sed -e "s#refs/tags/testing/v##" -e "s/_\([a-z]\)/-\1/" -e "y/_/./")
          ls -al pkg
          7z x pkg/ruby-${TARGET_VERSION}.zip ruby-${TARGET_VERSION}/revision.h
          cat ruby-${TARGET_VERSION}/revision.h
          7z l pkg/ruby-${TARGET_VERSION}.zip ruby-${TARGET_VERSION}/ChangeLog
      - name: Upload s3
        run: |
          set -x
          TARGET_VERSION=$(echo $GITHUB_REF | sed -e "s#refs/tags/testing/v##" -e "s/_\([a-z]\)/-\1/" -e "y/_/./")
          for ext in .tar.gz .tar.bz2 .tar.xz .zip; do
            aws s3 cp "pkg/ruby-${TARGET_VERSION}$ext" "s3://ftp.r-l.o/pub/tmp/ruby-${TARGET_VERSION}$ext" --no-progress
            curl -sS -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/tmp/ruby-${TARGET_VERSION}$ext"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}
      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "attachments": [{
                title: "Test Release ${{ github.ref }}",
                title_link: "https://cache.ruby-lang.org/pub/tmp/",
                "text": "${{ job.status }}: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ github.workflow }}> ",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SNAPSHOT_SLACK_WEBHOOK_URL }}
        if: failure()
      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "attachments": [{
                title: "Test Release ${{ github.ref }}",
                title_link: "https://cache.ruby-lang.org/pub/tmp/",
                "text": "${{ job.status }}: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ github.workflow }}>",
                "color": "good"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SNAPSHOT_SLACK_WEBHOOK_URL }}
        if: success()
