name: make-snapshot

on:
  schedule:
    - cron: '5 1-22/3 * * *'
  push: # for test
    branches:
      - '*'

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git bison autoconf ruby p7zip-full curl
      - name: Checkout ruby/ruby
        run: git clone --single-branch --shallow-since='2018-12-25 00:00:00' https://github.com/ruby/ruby ruby
      - name: Fetch notes
        run: cd ruby && git fetch origin +refs/notes/commits:refs/notes/commits
      - name: Make snapshot
        run: ruby ruby/tool/make-snapshot -archname=snapshot -srcdir=ruby pkg
      - name: Check pkg
        run: |
          set -x
          ls -al pkg
          7z x pkg/snapshot.zip snapshot/revision.h
          cat snapshot/revision.h
          7z l pkg/snapshot.zip snapshot/ChangeLog
      - name: Upload s3
        run: |
          set -x
          for ext in .tar.gz .tar.bz2 .tar.xz .zip; do
            aws s3 cp "pkg/snapshot$ext" "s3://ftp.r-l.o/pub/ruby/snapshot$ext"
            curl -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/ruby/snapshot$ext"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}

  stable-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git bison autoconf ruby p7zip-full curl
      - name: Checkout ruby/ruby for tool/make-snapshot
        run: git clone --depth=1 https://github.com/ruby/ruby ruby
      - name: Checkout ruby_2_6
        run: git clone --single-branch --shallow-since='2017-12-25 00:00:00' --branch=ruby_2_6 https://github.com/ruby/ruby ruby_2_6
      - name: Fetch notes
        run: cd ruby_2_6 && git fetch origin +refs/notes/commits:refs/notes/commits
      - name: Make stable-snapshot
        run: ruby ruby/tool/make-snapshot -archname=stable-snapshot -srcdir=ruby_2_6 pkg stable
      - name: Check pkg
        run: |
          set -x
          ls -al pkg
          7z x pkg/stable-snapshot.zip stable-snapshot/revision.h
          cat stable-snapshot/revision.h
          7z l pkg/stable-snapshot.zip stable-snapshot/ChangeLog
      - name: Upload s3
        run: |
          set -x
          for ext in .tar.gz .tar.bz2 .tar.xz .zip; do
            aws s3 cp "pkg/stable-snapshot$ext" "s3://ftp.r-l.o/pub/ruby/stable-snapshot$ext"
            curl -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/ruby/stable-snapshot$ext"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}

  snapshot-master:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git bison autoconf ruby p7zip-full curl
      - name: Checkout ruby/ruby
        run: git clone --single-branch --shallow-since='2018-12-25 00:00:00' https://github.com/ruby/ruby ruby
      - name: Fetch notes
        run: cd ruby && git fetch origin +refs/notes/commits:refs/notes/commits
      - name: Make snapshot
        run: ruby ruby/tool/make-snapshot -archname=snapshot-master -srcdir=ruby pkg
      - name: Check pkg
        run: |
          set -x
          ls -al pkg
          7z x pkg/snapshot-master.zip snapshot-master/revision.h
          cat snapshot-master/revision.h
          7z l pkg/snapshot-master.zip snapshot-master/ChangeLog
      - name: Upload s3
        run: |
          set -x
          for ext in .tar.gz .tar.bz2 .tar.xz .zip; do
            aws s3 cp "pkg/snapshot-master$ext" "s3://ftp.r-l.o/pub/ruby/snapshot/snapshot-master$ext"
            curl -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/ruby/snapshot/snapshot-master$ext"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}

  snapshot-ruby_2_6:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git bison autoconf ruby p7zip-full curl
      - name: Checkout ruby/ruby for tool/make-snapshot
        run: git clone --depth=1 https://github.com/ruby/ruby ruby
      - name: Make snapshot-ruby_2_6
        run: ruby ruby/tool/make-snapshot -archname=snapshot-ruby_2_6 -svn pkg 2.6
      - name: Check pkg
        run: |
          set -x
          ls -al pkg
          7z x pkg/snapshot-ruby_2_6.zip snapshot-ruby_2_6/revision.h
          cat snapshot-ruby_2_6/revision.h
          7z l pkg/snapshot-ruby_2_6.zip snapshot-ruby_2_6/ChangeLog
      - name: Upload s3
        run: |
          set -x
          for ext in .tar.gz .tar.bz2 .tar.xz .zip; do
            aws s3 cp "pkg/snapshot-ruby_2_6$ext" "s3://ftp.r-l.o/pub/ruby/snapshot/snapshot-ruby_2_6$ext"
            curl -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/ruby/snapshot/snapshot-ruby_2_6$ext"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}

  snapshot-ruby_2_5:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git bison autoconf ruby p7zip-full curl
      - name: Checkout ruby/ruby for tool/make-snapshot
        run: git clone --depth=1 https://github.com/ruby/ruby ruby
      - name: Make snapshot-ruby_2_5
        run: ruby ruby/tool/make-snapshot -archname=snapshot-ruby_2_5 -svn pkg 2.5
      - name: Check pkg
        run: |
          set -x
          ls -al pkg
          7z x pkg/snapshot-ruby_2_5.zip snapshot-ruby_2_5/revision.h
          cat snapshot-ruby_2_5/revision.h
          7z l pkg/snapshot-ruby_2_5.zip snapshot-ruby_2_5/ChangeLog
      - name: Upload s3
        run: |
          set -x
          for ext in .tar.gz .tar.bz2 .tar.xz .zip; do
            aws s3 cp "pkg/snapshot-ruby_2_5$ext" "s3://ftp.r-l.o/pub/ruby/snapshot/snapshot-ruby_2_5$ext"
            curl -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/ruby/snapshot/snapshot-ruby_2_5$ext"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}

  snapshot-ruby_2_4:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git bison autoconf ruby p7zip-full curl
      - name: Checkout ruby/ruby for tool/make-snapshot
        run: git clone --depth=1 https://github.com/ruby/ruby ruby
      - name: Make snapshot-ruby_2_4
        run: ruby ruby/tool/make-snapshot -archname=snapshot-ruby_2_4 -svn pkg 2.4
      - name: Check pkg
        run: |
          set -x
          ls -al pkg
          7z x pkg/snapshot-ruby_2_4.zip snapshot-ruby_2_4/revision.h
          cat snapshot-ruby_2_4/revision.h
          7z l pkg/snapshot-ruby_2_4.zip snapshot-ruby_2_4/ChangeLog
      - name: Upload s3
        run: |
          set -x
          for ext in .tar.gz .tar.bz2 .tar.xz .zip; do
            aws s3 cp "pkg/snapshot-ruby_2_4$ext" "s3://ftp.r-l.o/pub/ruby/snapshot/snapshot-ruby_2_4$ext"
            curl -X PURGE -H "Fastly-Soft-Purge:1" "https://cache.ruby-lang.org/pub/ruby/snapshot/snapshot-ruby_2_4$ext"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}

  check-snapshot-master:
    needs: snapshot-master
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev bison- autoconf- ruby- git-
      - name: Download snapshot-master.tar.xz
        run: wget https://cache.ruby-lang.org/pub/ruby/snapshot/snapshot-master.tar.xz
      - name: Extract
        run: tar xf snapshot-master.tar.xz
      - name: Fixed world writable dirs
        run: |
          chmod go-w $HOME
          sudo chmod -R go-w /usr/share
      - name: Set ENV
        run: |
          echo '##[set-env name=JOBS]'-j$((1 + $(nproc --all)))
      - name: configure
        run: cd snapshot-master && ./configure
      - name: make
        run: cd snapshot-master && make $JOBS
      - name: make check
        run: cd snapshot-master && make -s $JOBS check
