name: update_index

on:
  schedule:
    - cron: '17 1-22/3 * * *'
  repository_dispatch:
    types: "update_index"

jobs:
  update_index:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y ruby bundler
      - name: Checkout ${{ github.repository }}
        run: git clone --depth=1 https://github.com/$GITHUB_REPOSITORY .
      - uses: actions/cache@v1
        with:
          path: tool/snapshot/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Bundle install
        run: |
          cd tool/snapshot
          bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Update index
        run: |
          cd tool/snapshot
          bundle exec ruby update_index.rb
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FTP_R_L_O_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FTP_R_L_O_AWS_SECRET_ACCESS_KEY }}
      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "attachments": [{
                "text": "${{ job.status }}: <https://github.com/${{ github.repository }}/actions/?query=workflow%3A${{ github.workflow }}|${{ github.workflow }}> ",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SNAPSHOT_SLACK_WEBHOOK_URL }}
        if: failure()
